# Generated by Django 4.1.5 on 2023-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0002_alter_blogpublications_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpublications',
            old_name='full_text',
            new_name='full_text_1',
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_2',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_3',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_4',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
