# Generated by Django 4.1.5 on 2023-02-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0003_rename_full_text_blogpublications_full_text_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_10',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_5',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_6',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_7',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_8',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpublications',
            name='full_text_9',
            field=models.TextField(default=1, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
